SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

--remove a procedure para ser recriada
IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'STP_USUARIO_ALTERAR')
    DROP PROCEDURE dbo.STP_USUARIO_ALTERAR
GO

CREATE PROCEDURE STP_USUARIO_ALTERAR
    @SQ_USUARIO INT,
    @NM_USUARIO VARCHAR(200),
    @DS_EMAIL VARCHAR(200),
    @DS_SENHA VARCHAR(15)
AS
SET NOCOUNT ON;
--INICIO CODIGO

    DECLARE @SQ_REGISTRO_ENCONTRADO INT

    SET @SQ_REGISTRO_ENCONTRADO = (SELECT TOP 1 SQ_USUARIO 
                                   FROM TB_USUARIO
                                   WHERE SQ_USUARIO = @SQ_USUARIO)

    IF @SQ_REGISTRO_ENCONTRADO IS NULL
    BEGIN
        SELECT 'Aviso' AS CT_TIPO, 'Usuário não encontrado' AS CT_MENSAGEM
    END
    ELSE	---EM CASA: FAZER VERIFICAÇÃO SE JÁ TEM ALGUM EMAIL IGUAL AO PASSADO
    BEGIN
        UPDATE TB_USUARIO
        SET NM_USUARIO = @NM_USUARIO, DS_EMAIL = @DS_EMAIL, DS_SENHA = @DS_SENHA
        WHERE SQ_USUARIO = @SQ_USUARIO
    END

--FIM
SET NOCOUNT OFF
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO