SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

--remove a procedure para ser recriada
IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'STP_USUARIO_EXCLUIR')
    DROP PROCEDURE dbo.STP_USUARIO_EXCLUIR
GO

CREATE PROCEDURE STP_USUARIO_EXCLUIR
	@SQ_USUARIO int
AS
SET NOCOUNT ON;
--INICIO CODIGO

    DECLARE @SQ_REGISTRO_ENCONTRADO INT

    SET @SQ_REGISTRO_ENCONTRADO = (SELECT TOP 1 SQ_USUARIO 
                                   FROM TB_USUARIO
                                   WHERE SQ_USUARIO = @SQ_USUARIO)

    IF @SQ_REGISTRO_ENCONTRADO IS NULL 
    BEGIN
        SELECT 'Aviso' AS CT_TIPO, 'Usuário não encontrado' AS CT_MENSAGEM
    END
	ELSE
	BEGIN
			DELETE FROM TB_USUARIO WHERE SQ_USUARIO = @SQ_USUARIO

			-- retorno da procedure
			SELECT 'Sucesso' AS CT_TIPO, 'Registro incluido com sucesso' AS CT_MENSAGEM
	END

--FIM
SET NOCOUNT OFF
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO