SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--remove a procedure para ser recriada
IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'STP_PUBLICACAO_INCLUIR')
    DROP PROCEDURE dbo.STP_PUBLICACAO_INCLUIR
GO

CREATE PROCEDURE STP_PUBLICACAO_INCLUIR
(
	@SQ_USUARIO INT,
    @NM_PUBLICACAO VARCHAR(200),
    @DS_CONTEUDO VARCHAR(MAX)
)
AS
SET NOCOUNT ON;
--INICIO

	INSERT INTO TB_PUBLICACAO
	(
		SQ_USUARIO, 
		NM_PUBLICACAO, 
		DS_CONTEUDO, 
		DS_DATA_PUBLICACAO
	)
	VALUES
	(
		@SQ_USUARIO,
		@NM_PUBLICACAO,
		@DS_CONTEUDO,

	)

IF @RESULTADO IS NULL
BEGIN
     SELECT 'Aviso' AS CT_TIPO, 'Inclusão Não Realizada.' AS CT_MENSAGEM
END
ELSE
BEGIN
    SELECT 'Sucesso' AS CT_TIPO, 'Publicação inserida com sucesso.' AS CT_MENSAGEM
END

--FIM
SET NOCOUNT OFF
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO